# show raw goods
GET http://localhost:3000/
###

# filter task1
GET http://localhost:3000/task1?field=type&value=socks
###

# max price task2
GET http://localhost:3000/task2
###

# normalizer task3
GET http://localhost:3000/task3
###


# Uploader
POST http://localhost:3000/upload HTTP/1.1
content-type: application/json

[
    {
       "type":"socks",
       "color":"red",
       "quantity":9,
       "priceForPair":"$3"
    },
    {
       "type":"socks",
       "color":"green",
       "quantity":5,
       "priceForPair":"$10"
    },
    {
       "type":"socks",
       "color":"blue",
       "quantity":8,
       "priceForPair":"$6"
    },
    {
       "type":"hat",
       "color":"red",
       "quantity":7,
       "price":"$5"
    },
    {
       "type":"hat",
       "color":"green",
       "quantity":0,
       "price":"$6"
    },
    {
       "type":"socks",
       "color":"blue",
       "priceForPair":"$6"
    },
    {
       "type":"socks",
       "color":"red",
       "quantity":10,
       "priceForPair":"$3"
    },
    {
       "type":"socks",
       "color":"white",
       "quantity":3,
       "priceForPair":"$4"
    },
    {
       "type":"socks",
       "color":"green",
       "priceForPair":"$10"
    },
    {
       "type":"socks",
       "color":"blue",
       "quantity":2,
       "priceForPair":"$6"
    },
    {
       "type":"hat",
       "color":"green",
       "quantity":3,
       "price":"$5"
    },
    {
       "type":"hat",
       "color":"red",
       "quantity":1,
       "price":"$6"
    },
    {
       "type":"socks",
       "color":"blue",
       "priceForPair":"$6"
    }
 ]
###
